version: "3"
services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 
      MYSQL_ROOT_PASSWORD: "012012012"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - apps-network
    volumes:
      - .docker/mysql/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    links:
      - mysql:db
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: "012012012"
    networks:
      - apps-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - apps-network
    volumes:
      - .docker/nginx/config.d/:/etc/nginx/conf.d/

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - .docker/redis:/data
    networks:
      - apps-network

volumes:
  service:
networks:
  apps-network:
    external: true
